### ISSUE TITLE
Blog - people attribution rather than most popular

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#30]
Blog articles are supposed to pull in people with relevant skillsets to the topic on the right hand side. 

So the categories that they tag an article with need to pull in the ‘position’ filter rather than the ‘most popular article’ filter.

**Comment by paul-headington** [comment]
Not sure what you're meaning here. 

The discussed functionality was to have the "articles" e.g. Business law/personal law pages attached to people to link skillsets.

the "helpful reading" was not spec'd to link to users, and as such doesn't have a people panel.

Are you asking to add a people panel to a blog post like the article page? and add a link between posts and people's position?

If so that is out of scope and I'd have to charge for.

**Comment by michaellevans** [comment]
Maybe cost it up in case they want it. I’ll push back but if they want it they just need to pay for it – but they’ll need to know what it costs?
